WIP: New operation screen
Valter4578/bonsai. pull request #23
Opened 2022-01-23 18:47 UTC by VladimirBrejcha

2022-06-19 14:31 UTC, antonhoang approved these changes

2022-06-23 16:35 UTC, Valter4578 commented on bonsai/Views/FlexibleView/FlexibleView.swift
> +/// and pass it down to the real implementation, `_FlexibleView`.
At the first glance I don't see any reasons to divide this view into two classes. I'll try to combine them myself and figure out why they're divided

2022-06-23 16:37 UTC, Valter4578 commented
<img width="328" alt="Screenshot 2022-06-23 at 23 35 27" src="https://user-images.githubusercontent.com/38043698/175350038-ec48da97-ab05-4b7f-9089-6497afd2cb73.png">
I don't like standard Colors for nav bar button in the screen where we create a new tag. It stands out a lot. Make them purple like on previous screen.

2022-06-23 16:37 UTC, VladimirBrejcha commented
@Valter4578 Ебать где софты

2022-06-23 16:38 UTC, Valter4578 commented
![Simulator Screen Shot - iPhone 13 - 2022-06-23 at 23 37 30](https://user-images.githubusercontent.com/38043698/175350368-a6421a9b-5cbe-40e0-8b9b-fa0928fbfaea.png)
Incorrect placeholder behaviour. When text field selected there are both cursor and placeholder

2022-06-23 16:40 UTC, Valter4578 commented
![Simulator Screen Shot - iPhone 13 - 2022-06-23 at 23 39 22](https://user-images.githubusercontent.com/38043698/175350713-8ccfb65d-dcd7-439a-a3dc-94fa55edf0d7.png)
Same problem with new category screen. Standard nav bar buttons' colours.

2022-06-23 16:41 UTC, Valter4578 commented
<img width="323" alt="Screenshot 2022-06-23 at 23 41 17" src="https://user-images.githubusercontent.com/38043698/175351070-7e2f94b5-7531-488b-a5d1-f36ddcb82727.png">

The whole button isn't selectable. Only area with arrow and text. Whitespace should be clickable too

2022-06-23 16:43 UTC, Valter4578 commented
In general, really good work. But there are a couple of small improvements needed.

2022-06-23 16:45 UTC, Valter4578 requested changes
In general, really good work. But there are a couple of small improvements needed.

2022-06-25 17:11 UTC, VladimirBrejcha commented
> ![Simulator Screen Shot - iPhone 13 - 2022-06-23 at 23 37 30](https://user-images.githubusercontent.com/38043698/175350368-a6421a9b-5cbe-40e0-8b9b-fa0928fbfaea.png)
> Incorrect placeholder behaviour. When text field selected there are both cursor and placeholder

Minor, not sure that fix needed. Lets leave it yet

2022-07-02 07:39 UTC, Valter4578 approved these changes

2022-07-02 08:09 UTC, merged